[build]
builder = "NIXPACKS"
buildCommand = "pnpm prisma generate && pnpm run build"

[build.nixpacksPlan.phases.install]
cmds = ["m -rf .next && rm -rf node_modules && rm pnpm.lock.yaml && pnpm install --no-frozen-lockfile"]

[deploy]
startCommand = "pnpm run start -H ::"