[build]
builder = "NIXPACKS"
buildCommand = "pnpm prisma generate && pnpm run build"

[build.nixpacksPlan.phases.install]
cmds = ["pnpm install --no-frozen-lockfile && echo bunda"]

[deploy]
startCommand = "pnpm run start -H ::"