[build]
builder = "NIXPACKS"
buildCommand = "pnpm prisma generate && pnpm run buid"

[build.nixpacksPlan.phases.install]
cmds = ["pnpm install --no-frozen-lockfile"]

[deploy]
startCommand = "pnpm run start -H ::"